import { Libre_Caslon_Text } from "next/font/google";
import "./globals.css";
import "app/sass/globals.sass";
import { Header } from "app/components/shared/Header";
import localFont from "next/font/local";

const LibreCaslon = Libre_Caslon_Text({
  subsets: ["latin"],
  weight: "400",
});

const GoodSans = localFont({
  src: "../../public/fonts/Good-Sans-Regular.ttf",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${LibreCaslon.className} ${GoodSans.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
